### ISSUE TITLE
[Documentation / FAQ] Could a short subsection be added for ksquirrel versus sail?

### ISSUE THREAD

**Issue by rubyFeedback** [smoked-herring/sail#62]
Hey there,

I just found this project. I had ksquirrel in my local database for programs; ruby handles this.

I noticed I have not updated ksquirrel in 7 years so I checked whether it was still alive.

That was how I found sail. Now I have not yet tried to compile sail, will do in a bit,
but do you think it may be possible to briefly mention the main differences between
ksquirrel and sail in the FAQ?

https://github.com/smoked-herring/sail/blob/master/FAQ.md

This does not have to be long; just perhaps a sentence or two explaining the main
differences (I assume qt version and kde version?) and perhaps any other larger
difference between the two projects. Thank you for reading and perhaps considering!

**Comment by smoked-herring** [comment]
Hi! 🙂 Thanks for the request!

Let me clarify a little bit: SAIL is a development library containing image codecs, nothing else. It's not a UI application. SAIL is a successor of ksquirrel-libs (C++ image codecs) in particular and this is already mentioned in the FAQ. KSquirrel is dead for now, and no chance to revive it in the near future.
