### ISSUE TITLE
How to get alpha channel from png image

### ISSUE THREAD

**Issue by normandwilliams** [smoked-herring/sail#63]
Hello, I fail to see how I could extract the alpha channel from a PNG. I need to get the raw bits of only the alpha channel. Any idea is welcome, thanks

**Comment by smoked-herring** [comment]
Hi! Unfortunately extracting specific color planes is not currently supported (and not in my TODO for now). With SAIL, you can only extract all color components at once.

**Comment by normandwilliams** [comment]
ok, that is unfortunate (for me !) But thank you for the quick response. This is a nice product you have there.
